language: python
python:
- '3.5'
script: ''
install: ''
deploy:
  provider: pypi
  user: dannyzeep
  on:
    tags: true
    distributions: sdist bdist_wheel
    repo: dannyzed/combine-tex
  password:
    secure: pC0UTvcKU9kUq6xc+H5sSYymarpLvXVQzu00PcL3pWDCXUTlVmlWr5gJ1+aCzxQ80kQlBpMlGdQ8NF+XANa90XMWTvH/XLLtbohV3E4IN9UjafGE7sARIrmgHC6HESlAWE7A60eZv9ia9I+2vPHproE0DM+F+zRlNDHoKiLG4AQUQ5Djr01CIgbEVi6xYrC+MkkZZNvTf8eUILq9XiqLGXpKgf8YBIhNtfQZknYUkBi5mt/pwHw+/CuMaNE1ovLsYxp0CFwNBR24XEwK1Mp4Exvws1sRPJk5bY7nWbdGb7/kgMyKq3s8fr3Qkdkd5FxGqnOKsxZNumDCDw5ywxjHENpCRxZ9DH84t6JJ1tp0u/5x2WAEyAiWVMPVXIZAODBv40oEfBnVlpwU8y3dTxUOXDXrUdMtGrwzI1Xurwl7L5W2WYKQ3/AZFUxQWqdnMsfRnEk1kv01UdSSfqeq7qeFgyq+obaqbJBFn/wb02UlWhSBgDvif7PfN7maCXZYih3cit1RgeE7jA/nTLcbxlvnB6HxWGxTNnR/z290JVuosFJkTd4xd0B9rpz/c0Go501Fm8pV0ozbIgtcRz1mDDJEZyi/EvOXEP5TkKJBV1DxTpoKISgLKMfd6JQEgARSfyYvaIXZ8qOR0o7uGQgv9iNkifmG8jX7F3I6mPHLOZS6U/E=
